language: node_js
services:
  - redis-server
node_js:
  - "5.0"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  
after_script: NODE_ENV=test istanbul cover test/test.js --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage