language: node_js
services:
  - redis-server
node_js:
  - "5.0"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  
after_script: NODE_ENV=npm bin /istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./test/* && node node_modules/coveralls/bin/coveralls.js < coverage/lcov.info